### ISSUE TITLE
Home brewery will not create a new brew

### ISSUE THREAD

**Issue by Tazykat** [stolksdorf/homebrewery#114]
**If you are suggestting a feature or improvement**, delete everything here and just write your idea.

If you are reporting a bug, please fill out the details. If you don't I will most likely just close the issue asking for more detail.

---

**Browser Type/Version**: [Safari 9.1]

**Operating System**: [Mac OSX El Capitan]

**Issue Description**: [Create brew DOES not work]

You closed it down? Perhaps the worst example of customer service ever. I couldn't even respond? I just woke up. it is 8am here now. I am supposed to do it in my sleep. Create brew does not work. I have tried several times. Closed Browser and tried again. reset computer and tried. The "create brew Button does not load for me nor do any of the tools buttons work. 
**Brew code to reproduce**:

```
PUT YOUR BREW CODE HERE
```

**Related Images** : [IF APPLICABLE]

**Comment by stolksdorf** [comment]
You can continue commenting on a closed issue. I closed the previous issue because you did not provide me with any actionable details. After I received your issue I quickly tested creating brews on 3 different browsers, then checked my error logs for any widespread issues server or database related. After finding none, I decided to close it, since there's nothing more I could do, until you provide more more details.

On to your issue: Firstly I would suggest trying out Chrome. While the site should work on any browser (especially functionality like simply creating a new brew), I do my development and testing in Chrome. 

Secondly, you haven't told me what happens when you try to create a new brew. Does it go to a blank page? Does it do nothing? Does it throw an error? What page does it go to? Have you tried any other browsers? Maybe submit a screen shot? Anything? The problem seems very localized on your end. While I've been writing this comment over a two dozen people have created and saved new brews.

Lastly, you got to pay it forward man,

> You closed it down? Perhaps the worst example of customer service ever. I couldn't even respond? I just woke up. it is 8am here now. I am supposed to do it in my sleep. 

Comments like this make me sad and make you seem very entitled. I know that you aren't; you are just frustrated that a tool you wanted to use, to express your creativity and ideas, is not behaving like you expected. But please remember that I'm investing a fair amount of my time and money in providing this tool for you. I want to help you as much as I can. Don't make it harder for me to help you.

I'll leave this issue open so you can comfortably respond.

**Comment by Tazykat** [comment]
Well Scott, Firstly let me apologise for my impulsive response.

Yes it went to a page without any pages on it. It was blank. The tools froze.

I went to Chrome as you suggested and this worked very well in the most part. I could do with some lessons though.

Here is an example of my work so far.

Matthew

> http://www.naturalcrit.com/homebrew/share/rJA3_yPQ <http://www.naturalcrit.com/homebrew/share/rJA3_yPQ>
