### ISSUE TITLE
BookSanity Font replacement fails causing incorrectly displaying pages.

### ISSUE THREAD

**Issue by WIllem-K** [stolksdorf/homebrewery#150]
Browser: Chrome version 51.0.2704.103 m (64-bit)
[EDIT] Updated to version 51.0.2704.106 m (64-bit) still borked.
OS: Windows 8.0

In bundle.css on line 1 the definition for the .phb div class uses the fontfamily BookSanity.
Is this a standard font family that is supposed to be installed? Because I do not have it causing chrome to replace it with something incorrect.
I think it might be replacing it with Bookmania which I do have and I think that is classed as a similar font, but is apparently wider and completely messing up the formatting.
 
To demonstrate this I can simply show what the home brewery main page looks like for me:
![image](https://cloud.githubusercontent.com/assets/20374889/16710270/ebf38dfa-4628-11e6-94cf-3e9eca1c7b5d.png)
[same image at imgur](http://i.imgur.com/2P1oZ5L.png)

To solve:
Option 1: ~~In the CSS for .phb add serif or other smallspace fonts to the list of used fonts.~~
Scratch that, does not work, it replaces it with similar before moving on to the next font in the list.

Option 2: Have a hidden span filled with MMMMMMMMMMMM and measure how long that is in pixels with the BookSanity font, after the page loads have a javascript check if the hidden span is the expected length if it is not pop up a message to the visitor to download the font.

**Comment by stolksdorf** [comment]
The BookSanity font is embedded directly within the webpage. The site knows nothing about the Bookmania font, so even if you have it installed, nothing is being overwritten. Your issue is not font related.

Your issue is probably that your browser is zoomed in. Try resetting the zoom settings for the page.

**Comment by WIllem-K** [comment]
It was a zoom issue.
Wow, now I feel silly.

**Comment by stolksdorf** [comment]
Np, a few people have had this issue in the past, so it tickled my spidey sense. For more detail is _actually_happening is pixel rounding. So when you zoo, everything gets bigger but since everything has to render to pixels, so things get rounded up and some down. So when a bunch of these things round up, it will cause rendering issues. I've tried my best to mitigate it, but it's kinda impossible to stop.
