### ISSUE TITLE
Zoom affects layout negatively

### ISSUE THREAD

**Issue by Serifina** [stolksdorf/homebrewery#165]
**Browser Type/Version**: Chrome 52.0.2743.82

**Operating System**: Windows 7

**Issue Description**: Any change to the zoom level breaks pages, particularly if tables are located on them. Things will be relocated mostly or entirely off the page, rendering them unreadable.  I have to zoom most websites due to poor vision - text, in particular, is nearly always impossible to read at any comfortable distance from the screen at default zoom levels.

![screenshot](https://cloud.githubusercontent.com/assets/8071736/17389991/d53722c2-59d6-11e6-86c7-ea3714ca6146.png)

**Comment by stolksdorf** [comment]
I have already spent a fair amount of time getting it as good as it is now (it used to be way worse!). The issue is pixel rounding. I've converted most of the measurements in the CSS to make zooming better, but with complex layouts that are user created. 

If anyone has better solutions, please submit a PR.

**Comment by stolksdorf** [comment]
I just released a version,v2.3.0 that has improved rendering for the editor and Brew Renderer when you zoom. Hopefully that helps!
