### ISSUE TITLE
"Recent Brews" section still holds deleted brews.

### ISSUE THREAD

**Issue by sIllverback** [stolksdorf/homebrewery#169]
Not sure how easy this is to fix, or if it's possible, but it's mostly just a quality of life change, low on the list of priorities. Deleted brews still show up in the "recent brews" section, but clicking on them directs to a blank error page. I don't know if it's intended or if the brews should disappear. Even an old brew from months ago is still under my recently edited brews.

---

Browser Type/Version: Google Chrome Version 52.0.2743.116 m

Operating System: Windows 7 x64

Issue Description: Deleted Brews don't disappear from "recent brews." Clicking on the buttons direct to blank error pages.

Brew code to reproduce: None

**Comment by stolksdorf** [comment]
This isn't very easy to implement, since the recent list is just saved in your browser's local storage, it would be a huge pain in the ass to try to sync them and would probably lead to more trouble than it's worth. One solution is to add a little 'x' to remove recent entries, but misclicks would be very bad, especially if this list is the only way the user is recording their edit links. 

I have one idea I'll try later, I'll let you know if the UX works out.

**Comment by stolksdorf** [comment]
Recently stored brews will now be removed from your browser's memory if you you visit the deleted brew page. I think this is the best way to fix this issues :)

I also greatly improved how the Hombrewery handles error pages. 

Fixed in v2.3.0
