### ISSUE TITLE
Printing messed up

### ISSUE THREAD

**Issue by Wardrow** [stolksdorf/homebrewery#185]
**Browser Type/Version**: chrome

**Issue Description**: printing PDF messed up

**Brew code to reproduce**: <details><summary>Click to expand code</summary>

http://homebrewery.naturalcrit.com/share/r1Rx5_Ki
```
```
</details> This homebrew seems perfect, but when I try to export PDF/print it becomes messed up.

**Related Images** : [![kattura.png](https://s16.postimg.org/j7arvcohx/kattura.png)](https://postimg.org/image/qna1h5c75/)

**Comment by stolksdorf** [comment]
You have a few `</div>` in your code that are messing up the print view. Try removing them and let me know if that fixes it.

**Comment by Wardrow** [comment]
But I need them for the green boxes!

**Comment by stolksdorf** [comment]
I removed the `</div>`s and it renderers fine. Check it [here](http://homebrewery.naturalcrit.com/print/r1Yuu1oj). I wish you would have at least tried what I suggested instead of disagreeing with me. 

You can separate monster blocks that are followed immediately by noteblocks by using a "line break" tag, `<br />`, so you can remove your periods. Closing div tags, `</div>` should only be used in conjunction with an opening tag, `<div>`, otherwise my site will have trouble figuring out what your page is actually doing.
