### ISSUE TITLE
Spell List Not Vertical

### ISSUE THREAD

**Issue by Dfs101** [stolksdorf/homebrewery#186]
Hey, im a really big fan of the Homerbrewery and im just finishing my homebrew up but i was just wondering why the spell lists are made horizontal? It just makes it a little difficult to fit another spell list onto the page is all.

**Comment by stolksdorf** [comment]
As with most issue with this site, it comes down to how CSS Columns are implemented. Spell Lists are actually vertical, but the contents evenly distributed between all the columns. The browser does this when the height of the container is unknown, like with spell list. This doesn't happen with the page, since we know the height exactly and I can get the browser to fill the first column first.

I've tried several solutions, but none of them end of really working, hence why I didn't have a spell list for quite some time. So I don't know what to do, mixing columns within columns is bad-news-bears.

**Comment by Dfs101** [comment]
Ahh ok. Thank you for such a quick reply!

**Comment by stolksdorf** [comment]
Yeah sorry man. However, you you _know_ your spell list is going to take up a full page, use this instead `<div class='spellList' style='height:100%;column-fill:auto'>` and it should do what you want, but just use the whole page. Good luck!
