### ISSUE TITLE
Suggesting custom font setting

### ISSUE THREAD

**Issue by shadowevor** [stolksdorf/homebrewery#188]
Hi. First of all his is truly an excellent work, very helpful for me. Nice job. I've also pledged a little on patreon for my gratitude.

So here's the reason why I make this suggestion:
I'm currently using this tool to create materials of my game for my players to read. But since most of my players are not so good in reading English I made the content in Chinese. However the default font used by Homebrewery does not support Asian characters, making it using default font for Chinese which is very plain and unflavored. For now, I could change the fonts manually before printing by editing CSS in browser, but it is  inconvenient and sometimes mess up the layout since some fonts have slightly different sizes and I'll have to go back and readjusting layout. 

And here's my suggestion:
Maybe there could be a button or something to open a font-setting panel, enabling the user to use custom fonts to replace the original ones, overriding the CSS.

Thanks for taking your time. Hope it get even better.

**Comment by stolksdorf** [comment]
Thanks for the suggestion shadowevor. You can already easily add custom fonts to any brew. The Homebrewery allows you to embed custom CSS at the top of your brew and it will be included and used for rendering and printing. Find a flavourful font that supports the characters you need and include. You will probably have to tweak other things to make it look perfect, but I'm sure you can handle that.

As for creating a UI for uploading and using new fonts, I'm trying to avoid adding anymore UI or interaction as I can. I like to keep my products and simple and straight-to-the-point as possible. For example, I don't need to created an image uploader, parsing, and handler, because someone can use a service that is way better at that and just link it on here. 

Let me know how your work goes, and if you find a good solution maybe we could include it as a snippet others could use :)

**Comment by shadowevor** [comment]
I hadn't noticed I could use embedded custom CSS. It's works perfectly well
for me, thanks for the help!

2016-09-07 21:27 GMT+08:00 Scott Tolksdorf <notifications@github.com>:
