### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by carlosmrosas** [stolksdorf/homebrewery#204]
Hello, your tool is fantastic, thank you very much.

I would like to suggest a few things:

- Being able to edit spacing between lines
- Being able to edit font size
- Being able to change backgroung image to reflect PHB, DMG or MM
- Another thing is to justify the text, I do it using css, but some people don't know how to do it

The spacing I couldn't do using css, it only works on the headers but not on the text of text boxes and font size you could also do it using css but if there is a way for the average user to do it just clicking a button it would be awesome.

These are suggestions more on the usability side of things, I love your tool, it is fantastic, thank you again.

**Comment by stolksdorf** [comment]
Hey Carlos!

So all your suggestions are currently possible just using HTML and CSS. I don't plan on making this any easier for the user, because just using html/css provides more flexibility then I could ever add. 

This site continues to fill an interesting niche, since the "average user" IMO would only ever use Markdown and some of the snippets. As soon as you want to do custom images, spacing, and formatting, you leave the intended purpose of the site. That being said, I don't want to stop people from tweaking their pages, I've actually re-implemented large parts of the markdown renderer so it can handle HTML parsing bette, but when designing the UI/UX I view this as power-user features.

**Comment by vorpalhex** [comment]
Potentially a way to implement this while still keeping homebrewery mostly markdown based would be a CSS override box, potentially with some default styles pre-filled (so no need to lookup default classes). This would help keep the css on larger projects a bit neater, and also provide better usability.

Downside is that it'd still be a power user feature, and may not see much overall use.

**Comment by stolksdorf** [comment]
The CSS override box already exists. You can inject whichever styles you like into your brew by using `<style>` tags. Also if you are deciding to override specific CSS classes, I don't think a pain point would be looking them up. I would actually encourage the writer to do so, so they can understand what they are overwriting.
