### ISSUE TITLE
Preview/Share does not load for 1 file

### ISSUE THREAD

**Issue by mlenser** [stolksdorf/homebrewery#280]
Hi Scott,

One of my homebrews cannot show the preview or the share, but it works in print preview. The error is: "Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?"
<details><summary>Full Error</summary><code><pre>
Uncaught Error: Minified React error #32; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=32&args[]=52 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (libs.js:5)
    at a (libs.js:3)
    at u (libs.js:3)
    at d.getPublicInstance (libs.js:3)
    at f.attachRef (libs.js:2)
    at Object.addComponentAsRefTo (libs.js:4)
    at r (libs.js:4)
    at Object.a.attachRefs (libs.js:4)
    at d.r (libs.js:4)
    at e.notifyAll (libs.js:1)
</pre></code></details>

Please let me know if I can provide any additional details

### Additional Details

**Share Link** : rJOLlx_g

**Comment by stolksdorf** [comment]
Can you send me the edit link to your brew?

**Comment by mlenser** [comment]
Umm, I can't PM you here. Perhaps provide a different method to PM you it?
I think the editing link gives everyone access so probably not something I want to make public unless I decide to ditch that URL which I'd rather not as it's shared.

**Comment by stolksdorf** [comment]
Sorry, I meant share

**Comment by mlenser** [comment]
ah, I included just the id in the OP, sorry.

Here is the full link:
http://homebrewery.naturalcrit.com/share/rJOLlx_g

**Comment by stolksdorf** [comment]
Oops, I missed the share Id, I usually look for the share url :P

This is actually caused by issue #247. The issue is that certain HTML errors break the renderer on load and my fancy error handling doesn't even get a chance to load. I have a fix for it, but it requires upgrading several other parts of the project and I just haven't had time over the holidays.

A quick fix for you is to click 'Source', grab the code and paste it into a new brew. The Error Handler should kick in and tell you where all your HTML errors. Fix them and then you can paste back your code into your original brew in the editor. Save and reload and previewing should be back. 

Here's a screenshot of the errors in your brew. Just a bunch of unclosed tags, and you used several made-up HTML tags `<art>`, `<footerinner>` etc.

![image](https://cloud.githubusercontent.com/assets/387742/21861522/34e9c7f6-d803-11e6-88b2-bbf6e039ee4d.png)

**Comment by mlenser** [comment]
I cleared all the errors by editing it on a new brew. It works there, but the problem persists on the brew I linked above.
HTML5 supports custom tags. Is that a problem for the parser? Is that what is causing this specific issue?

Thanks for looking into this.

**Comment by stolksdorf** [comment]
I have not built my renderers, parsers, or error handlers to work with HTML5. I just support the Markdown spec. It looks like custom tags _should_ work, but I don't understand why you would use them.

**Comment by mlenser** [comment]
It seems to have started working now. I haven't changed anything from above, but perhaps it was some kind of cache issue or something esle.

Consider this resolved and thanks for your time and work on this project!
