### ISSUE TITLE
No more HTML?

### ISSUE THREAD

**Issue by dmmagic** [stolksdorf/homebrewery#296]
In the changelog it says:

"With the next major release of Homebrewery, v3.0.0, this tool will no longer support raw HTML input for brew code. Most issues and errors users are having are because of this feature and it's become too taxing to help and fix these issues."

I use a ton of HTML in my brews. SPANS and DIVS (with various classes), all my images are IMG tags, etc. How will these be handled going forward?

**Comment by stolksdorf** [comment]
Good question. Most elements will just be done in Markdown syntax rather than the HTML syntax. For things like `divs` I am creating a new syntax to create a classnamed div. For example to create a background image,

```markdown
{{titlePageBackground
  ![](http://linktomyimage.biz/cool.png)
}}
````
this would create the following rendered HTML

```html
<div class='titlePageBackground'>
   <img src='http://linktomyimage.biz/cool.png' />
</div>
```
Defining styles will be broken out into it's own editor, 
```css
.titlePageBackground img{
  position : absolute;
  top : 40px;
  left : 60px
}
```

**Comment by calculuschild** [comment]
I use a lot of HTML /CSS as well to get things to look how I want. It looks like youre planning to still allow custom css and classes then. Maybe that will work. Does a separate style editor mean we have a separate window open or something? Would a style editor support LESS?

**Comment by stolksdorf** [comment]
My goal with this change is to make easy things easier, and harder things harder. Right now the UI to access the style editor is to hit a toggle button in the snippet bar to toggle the editor to show the style code and back to the brew code. 

Having precise control over the look of your brew will probably get trickier or more verbose, but honestly that's not the goal of this tool. If you want that precise control, Photoshop and templates will provide a much better experience. 

And no support for less right now. The style overrides should be relatively simple.

**Comment by stolksdorf** [comment]
Also, @dmmagic you asked your question is such a great way, thanks! I've been really apprehensive/worried about this big change for the last 2 months, but I think it's going to be for the best for the future of the tool. I don't take removing features lightly.

This will let me refocus my time on new features, tools, and compatibility, rather than trying to squash obscure HTML bugs.

**Comment by dmmagic** [comment]
No problem at all! You've created a magnificent tool!

**Comment by stolksdorf** [comment]
I'll have more details when v3 gets closer to deploy.
