### ISSUE TITLE
Delete Brewery from User Page

### ISSUE THREAD

**Issue by vlos** [stolksdorf/homebrewery#309]
Right now the only way to delete a brewery is to edit it and then go to the menu to delete it.

I think it i would be better if the delete option was on the user's Brewery listing page with an icon below the edit (trashcan). Which prompted/confirmed the delete.

**Comment by stolksdorf** [comment]
Maybe, but deleting brews shouldn't be a very common operation, so I don't want to clutter the interface.

**Comment by calculuschild** [comment]
I second this. We've got cases even of broken brews from accidental HTML screwups (which hopefully will be a thing of the past with the new version), but they simply can't be deleted because the page can't fully load enough to include the delete button. As in this case: https://github.com/stolksdorf/homebrewery/issues/331

**Comment by stolksdorf** [comment]
Good call @calculuschild  . Another reason why I want to remove HTML support. Pushed v2.7.2 which has the option to delete a brew from the user page.

**Comment by calculuschild** [comment]
@stolksdorf Thank you sir. Works great! Minor thing, but I noticed the cursor doesn't change when hovering over the trash button though.
