### ISSUE TITLE
Problem with bulletted lists in Descriptive Text Boxes

### ISSUE THREAD

**Issue by Elik512** [stolksdorf/homebrewery#341]
I'm trying to create two bulleted lists inside a Descriptive Text Box and things are not behaving as expected.  At the base level, it appears to treat the bullet in the following line as a closing bullet to the previous line, which removes the bullets and make the previous lines italics.  There is some other weirdness going on, but i think that's the root problem.  Any suggestions?

### Additional Details

Here are a few examples of the problems
http://homebrewery.naturalcrit.com/share/Bye8gJIKe

or

Viewing the results of this code in this message looks different than on my Homebrew page.  This code was copied from the first example in the link above.

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

<div class='descriptive'>
##### Dwarf - Racial Features
* +2 Constitution
* Speed 25
* Darkvision
* Dwarven Resilience

##### Dwarf - Cultural Features
* Weapon Proficiencies: Battleaxe, Handaxe, Throwing Hammer, Warhammer
* Armor Proficiencies: Light and Medium
* Tools: Smith, Brewer, or Mason (choose 1)
* Stonecunning
* Languages: Dwarven, Common
</div>

</pre></code></details>

**Comment by calculuschild** [comment]
So, Markdown can use either asterisks (*), minus signs (-), or plus signs (+) to do bulleted lists. The problem is, it also uses asterisks on either side of text to create italics. So go ahead and try out using a - in place of the *, and it should work better.

@stolksdorf , I would imagine this tracks down to your "markdown.js". There you had some code to extract the HTML from within a div tag so it could parse the Markdown. I believe using "substring" there is also removing the extra whitespace such as newlines, and that's causing the asterisks to be interpreted as italics. Don't know if this is going to be handled differently in v3 though.

**Comment by Elik512** [comment]
Thank you very much @calculuschild.  That did the trick!!
