### ISSUE TITLE
Can't log in to NaturalCrit

### ISSUE THREAD

**Issue by KunYuL** [stolksdorf/homebrewery#349]
I can log in fine from my computer. But on my mobile, using the exact same credentials, username and password, will tell me I have an invalid match. I have the option to reveal password to check for typo, and my computer pass and my mobile pass match 100%, computer logs in, but mobile tells me its invalid.
I've also tried to log out from computer, and log in on mobile, still no success.
What am I doing wrong ?

**Comment by wizardsambolton** [comment]
The same is happening to me.

**Comment by tylermac** [comment]
Could we get a password reset link? Or a password change option?

**Comment by Raivias** [comment]
I'm having this problem too. I don't wanna loose my work by starting a new account either.

**Comment by ace1053** [comment]
This issue is happening to me as well, I have a theory, on my ipad it seems like i dont have an option to do a lower case letter for my username. I hope that this issue isn’t seriously a case sensitive issue =/ we will never be able to login on mobile unless we create the account on a mobile device and never log out.. have to transfer all those brews over....

**Comment by calculuschild** [comment]
Closing this now as a duplicate of #807 .

**Comment by ericscheid** [comment]
Might be a different issue of case sensitivity of username at login.

Unfortunately the login is at naturalcrit, not homebrewery, so not much we can do here. Right?

**Comment by calculuschild** [comment]
I do have access to the naturalcrit page if we need to fix stuff, but I don't know if this is even an issue anymore. I'm able to log in just fine on my phone and I have both lower and uppercase letters.

Unfortunately, I don't think we can make this case insensitive at this point, because we already have duplicate usernames that differ only by capitalization.
