### ISSUE TITLE
Column Break followed by Vertical Spacing doesn't work

### ISSUE THREAD

**Issue by Lv99Pangolin** [stolksdorf/homebrewery#378]
Title. The column break + spacing combo I use for formatting banner art and pictures isn't working any longer. The Vertical spacing doesn't work, anyway. Leaving the columns uneven or interfering with the art. 

It breaks the brew in Editor and Share, and I haven't finagled a fix yet. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
I don't think the Homebrewery has had any recent code changes that would affect it (I noticed this as well on my brews); it might be a change in the way Chrome is handling CSS now. For me, it looks like top and bottom margins are now being ignored for empty divs when placed at the beginning of any column other than the first. Mid-column is fine, but top of column doesn't work.

One option that worked for me is to simply change the divs I use for spacing to use padding rather than margins. It might work for you, but since you didn't post the "share" link to your brew its kind of hard to tell what exactly you are trying to do.

**Comment by Lv99Pangolin** [comment]
I figured out the problem (by trying to toy with the CSS). 

The way I did it was to always space out every line of wording (so it's just easier for me to read/pinpoint stuff) and the vertical spacing divs don't accept space between it and what it's spacing. (I have no clue how to say it correctly, but basically, example below)

The way I used to do it:

*****
<div style='margin-top:140px'></div>

Blah blah apples
*****
And that wasn't working anymore, so all my brews were messed up (because the margin wasn't working) So it works like this now

******

<div style='margin-top:140px'></div>
Blah blah apples

******

Literally, one line of spacing was the problem. XD. But, I fixed it. Went through all my past brews and fixed it too. So, thanks for the help! This is a case closed, now.
