### ISSUE TITLE
Password reset/recovery

### ISSUE THREAD

**Issue by Genxcide** [stolksdorf/homebrewery#412]
Hi, There needs to be some kind of password reset or recovery option. I have forgotten my password and the cookies have been cleared from my computer so I cannot get back into the brews I was working on. 

Also, there's no Log out/ sign out option that I can see. It's possible to Log in, but not log out. This seems like an issue.

Thanks.

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
There is [this hidden page](http://www.naturalcrit.com/login) with a logout button.

**Comment by stolksdorf** [comment]
I will not be adding a recovery option. It's a non-trivial task and would require me storing sensitive data for users.

**Comment by Boomboxcrab** [comment]
So I actually went through my 144 page document this morning and changed all the https to http, this worked fine for a while. But since I have gone away today and come back tonight, I have reloaded the file and none of the images work again. So I have no idea what is going on. Hope imgurs whitelist does fix it soon. I really need to get this stuff finished!
