### ISSUE TITLE
Adding "Class Features" duplicates whatever is above it under where the Class Features should be, and doesn't show the Class Features thing at all.

### ISSUE THREAD

**Issue by Retardi** [stolksdorf/homebrewery#413]
Whenever I try to add "Class Features" from the dropdown menu, homebrewery just makes multiple copies of whatever is in my brew (so if I have made 4 pages, it then duplicates those 4 pages once or twice or three times) and Class Features don't show up at all.

**Comment by calculuschild** [comment]
I have also noticed this issue.

**Comment by calculuschild** [comment]
@stolksdorf 

I would guess this is occurring due to "snippetbar.jsx" (line 71) passing in `this.props.brew` in as the `classname` variable in classfeature.gen.js. Without looking deeper I would guess it's taking in the entire text of the document and substituting that as the classname instead of generating a random one (archivist, fancyman, etc...) since it finds that the variable is already filled when it gets to line 5 of "classfeature.gen.js".

**Comment by stolksdorf** [comment]
This was an oversight when I was working on the Table of Contents generator. Fixed in v2.7.5.

**Comment by calculuschild** [comment]
This issue is still not fixed. See PR #687 for a fix.

**Comment by calculuschild** [comment]
This should be fixed now. Woohoo!
