### ISSUE TITLE
Problems converting A4 format brews to Letter brews

### ISSUE THREAD

**Issue by staticdrifter** [stolksdorf/homebrewery#439]
Having a real problem with converting brews formatted as A4 to Letter size. There's a simple click to put the A4 snippet in your brew, but once done, how do you convert back?
I have tried deleteing the snippet, but the pdf still comes out in A4 format. If I set the printing to Letter format, it still prints in A4 format.
Please help.

**Comment by calculuschild** [comment]
My guess is you have multiple copies of the A4 snippet hidden away in your
document somewhere, because deleting it is all you need to do. It also
always helps if you put your "share" link here so someone can actually look
at it. I don't know why nobody seems to read the instructions when filling
out these bug reports.

**Comment by calculuschild** [comment]
Closing since there hasn't been a reply from the user for a while and it is assumed the problem was solved.

If you are still experiencing this issue, feel free to reopen and provide information, @staticdrifter
