### ISSUE TITLE
Image Files-White Background

### ISSUE THREAD

**Issue by RohanJax** [stolksdorf/homebrewery#447]
When I attempt to insert an image file, (background image) my background is a white square box, even when I copy and paste your same beer stein example.  How do I get just the image figure, weapon, character, to show up without the white square box image?

Thank you
RohanJax

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by calculuschild** [comment]
Your "additional details" section of the report has not been filled out
properly. There is no way to help if we can't see what your code is doing.

**Comment by RohanJax** [comment]
I copied and pasted a screen shot of what I am seeing, and my code.  Hopefully it translates, and works.

Thanks


![image](https://user-images.githubusercontent.com/30243139/28289686-2b69421c-6b09-11e7-9e42-27b6f0f1ce67.png)




<img src='https://tse3.mm.bing.net/th?id=OIP.GnNKT882s4rWGNZtvxYitAEEEs&pid=15.1' style='position:absolute;bottom:50px;right:30px;width:280px' />

**Comment by calculuschild** [comment]
Without your actual code helping is really hard. The screenshot is too blurry to read any of the text.  Are you sure you can't just paste your code in here?

Looking at your screenshot though, my guess is that your image is showing that way because the image file actually has a white background on the image.  The beer stein in the front page example has a transparent background. I would suggest opening up Photoshop or Gimp and getting rid of the white background. [Pixlr.com](https://pixlr.com/editor/) is a free web-based tool that could do that as well. Save the file as a PNG and the transparent parts will stay transparent.

There is also [this tutorial](http://homebrewery.naturalcrit.com/share/B1Hju_QaTx) someone made which explains how you can try adding some CSS code to turn a white background transparent.  If it were me though I would just edit the image so its transparent on its own.

**Comment by RohanJax** [comment]
I tried pasting code, but it looks like just the image showed up, here it is again....  If this doesn't work, no worries.  I'll try your other methods.  Thanks.




<img src='http://fc08.deviantart.net/fs31/f/2008/217/3/5/kobold_by_Nordheimer.jpg' style='position:absolute;bottom:50px;right:30px;width:280px' />

**Comment by calculuschild** [comment]
Ok. Well yes, this image that you have here does have a white background which you will need to remove in an image editing program. That should solve your issue. Pixlr is great and free and you can do it in about 2 minutes.

**Comment by RohanJax** [comment]
Super, thanks.  I'll check that out.
