### ISSUE TITLE
My 52 page document now says 'can't get that' from share or edit links.

### ISSUE THREAD

**Issue by swordmeow** [stolksdorf/homebrewery#466]
What it says on the tin.

http://homebrewery.naturalcrit.com/share/rk7z5l1tlZ

**Comment by calculuschild** [comment]
Homebrewery does not store backups. Did you ever share the edit link with
someone? I lost a brew one time by accidentally posting the edit link on
Reddit instead of the share link. Someone visited the page, now they became
an editor, and could now delete the file. My guess is this is what
happened. Always always keep a backup in your own files.

I managed to find this version from a few days ago on Google's cache.

http://webcache.googleusercontent.com/search?q=cache:GNVKnhKv5hsJ:homebrewery.naturalcrit.com/share/rk7z5l1tlZ+&cd=1&hl=en&ct=clnk&gl=us&client=ms-android-att-us

Go there immediately and copy anything you can before it gets overwritten.
You won't be able to viee the Homebrewery code, but you can at least grab
all the text, and if you view the source code of the page, you can get the
rendered html which will help you reconstruct your file pretty quickly.

**Comment by swordmeow** [comment]
Thank you for the cache, I've copied it all now.  For what it's worth I never have shared the edit link - I posted the share to reddit months ago, and actually haven't given out either link recently.
