### ISSUE TITLE
Question regarding v3.0.0

### ISSUE THREAD

**Issue by PalaNolho** [stolksdorf/homebrewery#541]
"With the next major release of Homebrewery, v3.0.0, this tool will no longer support raw HTML input for brew code. All brews made previous to the release of v3.0.0 will still render normally."

Does this mean we will no longer be able to add images, divs and make all the cool effects we are able to do using HTML?

Is there a particular reason for this decision?
When can we expect the new v3.0.0 ?

many thanks

**Comment by HeruAsatru** [comment]
iirc @stolksdorf said that most of the help requests he gets boil down to someone fucking up the html in their brew, destroying it. i think he also stated that we will still be able to include images and such in v3, but there will be some markup-like code to do it, that shouldn't break the brew. 

there is no ETA for v3, as far as i know.

**Comment by PalaNolho** [comment]
Thanks

**Comment by stolksdorf** [comment]
Thanks for answering @HeruAsatru.

So images don't require HTML. I'm actually building a new Markdown engine that would allow div creation. Getting rid of HTML doesn't mean getting mean getting rid of CSS, which is where all those cool effects come from. @HeruAsatru nailed it with people just not understanding how to format HTML properly, and the HTML/Markdown spec being so loose that it's really hard to track down brew issues. Worst of all these little errors end up effecting the page, so it looks like it's an issue with Homebrewery, not with the formatting. It's incredibly tedious for me to make sure there's actually a bug versus just bad HTML, hence why there's so many outstanding issues on this project, I simply just can't vet them all (nor do I want to).

Re: v3. It's super side-tracked. There's like at least 40hrs of work to be done on it. Homebrewery was suppose to be a fun lil personal project, I never expected it to be so popular! 

V3 is me trying to actually approach the project professionally (tests, consistent API, better admin tooling, tighter rendering engine, backwards compatibility, faster DB reads/writes, upgrades to newer web tech, account integration with 3rd for recovery, reliable rendering, better security, etc. etc.), because of that the scope has grew a ton. It's hard to sequester away so much free time to make it happen.
