### ISSUE TITLE
Hijacked!

### ISSUE THREAD

**Issue by GorchD20** [stolksdorf/homebrewery#550]
Someone hijacked my largest (150 page) brew and replaced it with a single page. How can I revert it to the old version and/or get my account back under control? Are all accounts at risk? What is going on?

**Comment by DoctorDan1986** [comment]
Hopefully, you have that 150-page window still open on one of your devices.  If you do, you can simply press 'save', and it will replace the ganked version.

If not...well, I'm not sure you have any options.  With sympathy and respect, I would recommend that you make daily backups to at least two locations of the code.

**Comment by calculuschild** [comment]
Did you share the "edit" link somewhere? My guess is you posted the link
and someone looked at it which adds them as an author.

In that case, you might be able to goole search your brew and hopefully
google has a cached copy you can copy.

And in the future, never share your edit link. Only share the "share" link.

**Comment by calculuschild** [comment]
Since its already hijacked, you could paste the link here and i could try to see if google has a backup

**Comment by calculuschild** [comment]
Closing for now because of no further response from the user, and at this point the document is probably long gone.

Feel free to reopen this issue if you want to provide any links to your document so somebody can try to track it down. It's unlikely, but there may be something floating around still. @GorchD20
