### ISSUE TITLE
Redefining Class Table Column Width

### ISSUE THREAD

**Issue by BigDaddyLoveshack** [stolksdorf/homebrewery#568]
Hi,

I have been using HomeBrewery for my 3.5 stuff, and for the most part, it works great, but now I've come across an issue, which is the formatting for the Class Tables. Essentially I have a short column width for Level, Proficiency Bonus, then a super-wide one for Features, then spell tables.

I want to redefine column widths so I can replace Proficiency Bonus with BAB, add Reflex/Fort/Will saves, then Class Features, and then, if need be, spells.

Is there any way I can do this? I'm a bit of a numpty when it comes to Markup and I haven't been able to find an answer that works so far.

Cheers,
Rob

**Comment by DoctorDan1986** [comment]
I'm not familiar with 3.5, but you should be able to adjust the formatting easily.

The Table Functions are set up like so:

`##### Class Name <- the name of your class`
`|Feature Header 1| Header 2| etc. | <- column headers.  Each one is denoted by the pipe symbol pair "| |"`
`|:---:| <- column formatting.  ":---" is left justify, ":---:" is center justify, "---:" is right justify.  The number of these pipe-colon-hypen groups you make will determine how many columns are created.  If your class is 'wide', it will take up the width of the page, and thus, the more columns you make, the smaller their width.  The width of each column will generally auto-size to the longest text string you type...until you run out of room due to other columns.`

**Comment by BigDaddyLoveshack** [comment]
Hey Doc,

Thanks for the quick response.

I think I discovered what my issue was, which was that the auto-fill text in the Homebrewery table was determining the column width and I was trying to sort it out in the top lines rather than deleting the provided text.

Cheers for this mate!
Rob
