### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by Allmisc** [stolksdorf/homebrewery#581]
I can't log in and it's annoying. NaturalCrit has become an essential for me to use when doing my D&D prep and without it almost all my files are gone.

Whenever  I try to log in on my account even when writing the completely wrong name and password the only message shown is "Something Went Wrong" Please please please fix this. 

### Additional Details

**Share Link** :

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by Sadras1** [comment]
Having the same issues. Really hope this is temporary

**Comment by stolksdorf** [comment]
Sorry you were having some issues. I'm currently diagnosing the issue, but it looks to be resource related, so I've added some more resources and more in-depth logging to the login server. I want to assure you that your brews are not dependent on your account. Accounts are simply linked to brews, so if you keep the edit link you can still modify and share your brew even if you aren't logged in. 

I'll close this for now because it seems the issue has passed, but please re-open this if there are any more login issues in the future.

**Comment by Sadras1** [comment]
Thanks for this Scott – most appreciated!!!
