### ISSUE TITLE
Text and Table rendering issue

### ISSUE THREAD

**Issue by Finalplayer14** [stolksdorf/homebrewery#596]
Whenever I preview or share the document, the text, and table on the first-page shift upwards. This does not happen when I export it to a PDF. Any way to fix this without having to completely change the layout? 

http://homebrewery.naturalcrit.com/share/ByWH3eEccZ

**Comment by Sansd20** [comment]
replace your 1st page with the code from http://homebrewery.naturalcrit.com/share/By-RV3PMEM

Since the images are being placed exactly where you want them, they shouldn't be in the spacing DIV. 

This part is up to you, you may want to add `<style>
  .phb#p1:after{ display:none; } 
</style>`
To the top of the 1st page, this gets rid of the lower banner on page one.

**Comment by Finalplayer14** [comment]
Thank you. After doing that the shifting seems to have stopped. Though now when I try to make it into a PDF, the table seems to repeat the words "d10" and "Quirks", is there a way to fix that?

**Comment by calculuschild** [comment]
See #318 for a solution to the duplicated text.
