### ISSUE TITLE
My brew has reverted to an older version

### ISSUE THREAD

**Issue by Calavid** [stolksdorf/homebrewery#650]
I have 3 brews currently, 2 are mine and one is just a guide for how to use this tool that i found. anyhoo, i was editing my 2 last night and i came back this morning, both were fine, but i went to keep editing them now and one of them has reverted basically all the changes ive made since i made the document. i was transferring things over from another document so all i lost really was the formatting and the tables, as well as some small edits, but i would like to recover the lost document if possible.

### Additional Details

**Share Link** : http://homebrewery.naturalcrit.com/share/BkZPuUJHiG

or

**Brew code to reproduce** : <details><summary>Click to expand</summary><code><pre>

PASTE BREW CODE HERE

</pre></code></details>

**Comment by TheGreatWhy** [comment]
Literally just happened to me. Over one hour of work wasted. I noticed right after I shared I had lost all the edits, despite the auto save seemingly working perfectly.

**Comment by HeruAsatru** [comment]
If you have the document still open, you can try to CTRL+Z back, but not guarantees...

I once lost some progress on a brew. I had worked on it one day, saved, left the tab open but closed the browser, opened it the next day, continued to work, and lost a lot of stuff. Since then, I'm very careful to backup all my stuff. I have one text file per day per brew (example: beasts_20180322.md, magic_items_20180322.md, beasts_20180323.md, magic_items_20180323.md, ...). I work mostly in these files when writing new stuff. I only do formating stuff in the homebrewery, and when I do, I immediately copy everything into this file. I create a new file everyday when I start working on this. 

So far, this saved me from losing data twice!

**Comment by calculuschild** [comment]
This seems to be a common issue. For now, make frequent backups on your own machine by copying the text into a file. See #654.
