### ISSUE TITLE
[Homebrewery development] Setup gitter/discrord/slack/whatewer chat for contributors

### ISSUE THREAD

**Issue by AlexeySachkov** [stolksdorf/homebrewery#739]
Hi,

I would like to contribute to the project by implementing some new features, but I also would like to discuss implementation details/design/future roadmap with other contributors. 

I understand that some part of questions may be discussed in issues/pull requests, but sometimes it is easier to sync with other devs in some live chat than in issues, especially on some internal implementation details/work distribution across devs/etc.

@stolksdorf, @Rae2che5, @calculuschild (@schemen and @kkragenbrink maybe?), what do you think?
My proposal is gitter.im, but I'm okay with any other tool.

BTW, my current progress you can see here: [project board](https://github.com/AlexeySachkov/homebrewery/projects/1), [code](https://github.com/AlexeySachkov/homebrewery/commits/private/asachkov/lets-try-change-something)

**Comment by Rae2che5** [comment]
I definitely think we'd benefit from more direct discussions, as well as some kind of project board-style management. Thanks for suggesting it!

I think at the moment we're slightly held back by @stolksdorf's sporadic availability; for example, his would be the natural repo to attach a gitter channel to, but he's the owner and so we can't do it. Same thing for project boards: Project-wide issues would ideally live on the canonical fork.

How would people (especially @stolksdorf) feel about creating a GitHub organization for the primary fork? The current contributors could become organization admins, and we would take it from there. (Any ideas about a suitable name? `homebrewery` is sadly taken...)

**Comment by AlexeySachkov** [comment]
I think creating open-source organization for homebrewery development is a good idea!

If I understand correctly, all the content at naturalcrit.com is published on github:
* stolksdorf/naturalcrit
* stolksdorf/homebrewery

What about moving both of these repos to the `naturalcrit` (this name is available) organisation, owned by @stolksdorf?

**Comment by Rae2che5** [comment]
I've registered the `naturalcrit` name (@stolksdorf, please speak up if you would prefer us to stay away from it!), and invited @calculuschild and @stolksdorf as owners of the organisation, and @AlexeySachkov as a member.

**Comment by AlexeySachkov** [comment]
@stolksdorf, if you are not against of creating [naturalcrit](https://github.com/naturalcrit) organization, could you please **transer** [stolksdorf/homebrewery](https://github.com/stolksdorf/homebrewery) into the new organization?

[Transfer](https://help.github.com/articles/about-repository-transfers/) is mush more better than fork: we will have all existing issues and PRs + auto redirect from old the url

**Comment by Rae2che5** [comment]
Ah, that would indeed be better. I'll remove the existing fork that I created, as presumably it would name-clash with a potential transfer.

**Comment by LeviRosol** [comment]
Help me understand the desire of moving forward with this project when the maintainer has made it clear there is no interest in doing so on his part. It's been well over a year since anything has been pushed to production, and many many months since any activity has been seen on the project.

I'm positive all of you are aware of GM Binder. But to reiterate, it exceeds the features of HB by far, gets regular new features, and is actively being developed into an even more robust too. I understand that it's not open source so you can't run your own, but we've been very very open about our plans, and have been praised time and time again for listening to our user - both from a support standpoint, as well as from a feature request standpoint.

So help me understand - what is the appeal for you of HB over GMB? I realize we'll never be able to make 100% of the community happy, but I'm genuinely curious.

**Comment by Rae2che5** [comment]
> I'm positive all of you are aware of GM Binder. But to reiterate, it exceeds the features of HB by far, gets regular new features, and is actively being developed into an even more robust too. I understand that it's not open source so you can't run your own, but we've been very very open about our plans, and have been praised time and time again for listening to our user - both from a support standpoint, as well as from a feature request standpoint.

Speaking for myself, it's indeed as simple as that: GMB is not open-source. You're right that Scott isn't very active, but that doesn't matter, because the rest of us can step in and carry on. Nothing is lost. In contrast, if you decide you've had enough of GMB tomorrow, all content stored there is forever useless.

No amount of extra features is going to make up for that, I'm afraid.

> So help me understand - what is the appeal for you of HB over GMB? I realize we'll never be able to make 100% of the community happy, but I'm genuinely curious.

Perhaps you can help us understand -- how do you plan to make money from GMB? You seem to be heavily pushing a patreon page, but Scott also has one, which does just fine (well, clearly fine enough to keep the main server running). Do you ever plan to do anything more?

A related question: While of course it's your prerogative to keep GMB closed-source, could you explain why you don't open it up? I'm sure if you did plenty of people would feel much better about switching over, and I doubt you would lose any patreon revenue; in fact, you would probably gain some.

**Comment by LeviRosol** [comment]
Thanks for the follow up. I always feel really odd bringing up this topic here as I want to be respectful to the time / effort / knowledge that has been applied to HB. I am 100% ok with answering your questions (as i've answered them before for people), but I don't want to muddy this thread, or the HB issue tracker in general. Would it make sense for you to ask these in /r/gmbinder? Or should I just reply here?

**Comment by Rae2che5** [comment]
I'd say that ship has sailed, so please reply here; may as well keep the conversation in one place.

**Comment by LeviRosol** [comment]
Ok, so on the idea of one day GMB shutting down and the users lose everything:
GMB is supported my company. We're a dev shop in the midwest, and maintaining this app is negligible compared to the other work we do. Even if everyone stopped backing our patreon tomorrow, GMB would stay up for many years to come. I personally get enough value from it to keep it going.

*Clarifying, multiple devs in our office work on GMB in their free time. It's not just me. I just happen to be the face.*

I want to point out something about data though. If **either** service were to shut down tomorrow, you would be out of 100% of your data. Wayback Machine will be useful, but that's about it. HB being open source means nothing because you do not have access to the actual database. Yes, you can and should always back up your work, but the majority of users do not do this.

Regarding OSS - The primary reason that we do not open source GMB is because it uses components that we have, as a dev shop, created and use with our clients. I do think there's some squish in this answer, but ultimately it's the decision we came to. That being said, it is based on AngularJS, and we're doing less and less AngularJS work (more and more Angular), so maybe there's a case for it in the future.

And finally, revenue. We've done a ton of research / communication with the community to better understand what they want and / or are will to do. This is in the context of both features of GMB, as well as what they'd pay. We have been very clear that the core ability to create and share content will **always** be free for everyone. The end result was that a significant portion of the community is happy with the free services provided, and a smaller, but still reasonably sized part of the community is more than willing to pay $3 or $5 a month for more features and to support us.

We do currently have features that are patron only features, and do have a plan to migrate away from Patreon to our own monthly subscription (to reduce Patreon fees and because doing payment processing is something we are very familiar with). Doing so will not change what every user can do for free.

Bottom line is, we have no misconceptions of GMB ever being a self sustaining business. It's a fun side project that buys us beer, coffee, and cool stuff for our office campaigns. If we can work to recoup a fraction of the value of effort put into it, great!

---

Outside of all of this, here's my rub with with the idea of nursing along HB. Extrapolating from our numbers, I know that HB more than likely sees more than 200k unique visitors a month and has somewhere around 100k or more users who have created 250k documents or more (all my educated guesses). Those users have put an unimaginable amount of time into their content. Literally 100's of thousands of hours of collective time.

And if there's an issue? Nothing.

Imagine what would happen if Imgur cut off HB like they did GMB a few months ago. We spent some long nights working with Imgur staff to understand the issue, building a system to scrape images, host them, cache them, and then reprocess 65k documents (documents plus versions) for the new URLs.

Those of you who have stepped up to help maintain are awesome, don't get me wrong. But if you can't get your fixes to prod, it really doesn't help.

---

Again, I get why HB still exists and why people use it. HB is the incumbent and their's a lot of content out there causing the "network effect". Scott has also held to his word on keeping it alive. I have full faith that he will continue to do so. But to see people actively spend their time in HB when there is - and I guess this is simply my opinion - an equally available and more feature rich tool that is getting regular updates and has better community support, Why? And why would anyone encourage others who don't know the history to repeat that mistake?

---

I hope none of this comes off as snarky or disrespectful. It's not my intent. We all know that some times text doesn't carry inflection / emotion well. Although it has been quite some time since I've made many of these statements, I do think this needs to be my last. People will do what they want to do, and I can't stop them from making what I think is a poor decision. 

After all, it's just like, my opinion man...   :)

**Comment by Rae2che5** [comment]
Thanks for the reply. There's a lot of detail there, but it seems to boil down to "trust us, we'll keep doing this, although it's not our primary business". Like you, I don't mean to come off as disrespectful -- but you're explicitly describing it as a group of volunteers who happen to work together working on a project that's useful to them. That sounds like a great basis for an open-source project to me, but does not make for a closed-source project I would want to invest creative time with.

For the record, of course data stored in HB.com's database is not safe from disappearance. The difference is that I have all of my markdown sources locally, and can always recreate the rendered output even if it goes away; in contrast, if GMB goes away, all my markdown sources become useless.

**Comment by AlexeySachkov** [comment]
Hi, @LeviRosol 

> Help me understand the desire of moving forward with this project when the maintainer has made it clear there is no interest in doing so on his part.

I'm not a real user of Homebrewery - I have been looking at the project for some time and now I decided to contribute into it. As I understand Homebrewery users are still exists and I can make them more productive and happy by developing new features. You are right: there are some problems with pushing new changes to the prod, but I think all of them can be solved by communicating with @stolksdorf. 

I'm not interested in GMBinder, because I don't need to create custom rule-books. But when I need such - I will use Homebrewery, because I already familiar with this tool: I can tweak and improve it for my own needs. Also I might contribute to the GMBinder too, but it is not open-source.

**Comment by calculuschild** [comment]
Anyway, if we jump back to the original topic:

I saw @AlexeySachkov has been trying to contact @stolksdorf . I have also sent him emails and PM'ed his reddit account, but alas, no replies so far.

Are we able to set up gitter.im on our github organization at this point or do we need to link it to the repo itself? It looks like gitter can work either way, and it would be nice to get some of this discussion out of the issues tracker.

**Comment by schemen** [comment]
Regarding production hosting; I could easily provide hosting for the site as it's already running on my swarm cluster, if you want that. What's missing is all the natural crit connection, no login and so on.

**Comment by AlexeySachkov** [comment]
> Are we able to set up gitter.im on our github organization at this point or do we need to link it to the repo itself?

@calculuschild, it is possible to create gitter chat for github organization and you should be able to do it by yourself as organization owner. I think we can start without linking a repo

**Comment by calculuschild** [comment]
Ok guys. I set up a gitter chat for the naturalcrit organization and invited everyone there. Maybe we can start moving this discussion over there.

**Comment by Pardalis66** [comment]
My issue is I've been a GM for 41 years I have all the software tools available for cartography from a half-dozen companies I've never heard of GM binder what is it how much does it cost what are its features just give me a link somewhere that's not a subreddit / R something... I'm looking for a website with some hard information.

I've been involved with roll20 since its Inception and before that open RPG with python and before that web RPG and I've never heard of this GM binder so whoever is doing your ads they're not reaching hard core GM's that are on roll20 for whatever reason or I've never heard of it it mentioned in any blogs or videos from famous to semi-professional gamemaster's. Thanks.

**Comment by AlexeySachkov** [comment]
Hi, @Pardalis66 

Here you go: https://www.gmbinder.com

AFAIK, GMBinder is a tools similar to Homebrewery which allows you to create and share "your favorite tabletop RPG documents"

**Comment by calculuschild** [comment]
Closing this... the Gitter page and github org are set up.
